name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-config-pull]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "::group::foo"
          echo "Hi"
          echo "::endgroup::"
