name: Manual
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Write date
        run: |
          echo "${{ steps.date.outputs.date }}" > modified.tstmp
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        if: ${{ success() }}
        with:
          title: 'Automatic PR for ${{ github.event.number }} - @${{ github.actor }}'
          commit-message: 'Creating PR for #${{ github.event.number }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: automatic_pull_${{ steps.date.outputs.date }}_${{ github.event.number }}
          delete-branch: true
          base: main
          body: 'Relates to #${{ github.event.number }}'
