name: Manual
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%s')"
      - name: Write date
        run: |
          echo "${{ steps.date.outputs.date }}" > modified.tstmp
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        if: ${{ success() }}
        with:
          title: 'Automatic PR for ${{ github.event.number }} - @${{ github.actor }}'
          commit-message: 'Creating PR for #${{ github.event.number }}'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: automatic_pull_${{ steps.date.outputs.date }}_${{ github.event.number }}
          delete-branch: true
          base: main
          body: 'Relates to #${{ github.event.number }}'
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@86ad1c0121411bd92c04ddf493434540de5a20e2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
      - name: Trigger CI for Pull Request
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: dhadka/test-python
          event-type: auto-config-pull
          client-payload: '{"ref": "refs/pull/${{ steps.cpr.outputs.pull-request-number }}/merge"}'
